services:
  api:
    image: merchantportal-api-x86
    container_name: merchantportal-api
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - RUST_LOG=${RUST_LOG:-info}
      - MODE=${MODE:-prod}
      - RUST_BACKTRACE=${RUST_BACKTRACE:-0}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CORS_ALLOWED_METHODS=${CORS_ALLOWED_METHODS}
      - CORS_MAX_AGE=${CORS_MAX_AGE:-3600}
      - LOG_FORMAT=${LOG_FORMAT:-pretty}
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-50}
      - RATE_LIMIT_WINDOW_SECONDS=${RATE_LIMIT_WINDOW_SECONDS:-60}
    restart: unless-stopped
